### ISSUE TITLE
Failed to resolve: de.stuermerbenjamin:remotecamera-free:<latest-version>

### ISSUE THREAD

**Issue by ifananomali** [thebino/cameraremotelibrary#1]
Hi!

I want to use your library, but when syncing gradle, I got an error 'Failed to resolve: de.stuermerbenjamin:remotecamera-free:<latest-version>'. Is it public already?

Thanks

**Comment by thebino** [comment]
Sorry the package identifier has been changed. Please update it to

```
implementation("de.stuermerbenjamin:cameraremote-free:<latest-version>")
```
